# Generated by Django 2.1.5 on 2020-03-22 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytutor', '0007_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_teachers', to='mytutor.User')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_students', to='mytutor.User')),
            ],
        ),
    ]
