# Generated by Django 2.1.5 on 2020-03-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytutor', '0008_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
