# Generated by Django 2.1.5 on 2020-03-22 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytutor', '0011_auto_20200322_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytutor.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytutor.User')),
            ],
        ),
    ]
